### ISSUE TITLE
PDF: integrate the totals in the table

### ISSUE THREAD

**Issue by Segelzwerg** [Segelzwerg/Rechnung#174]
![image](https://github.com/user-attachments/assets/ca912027-55fc-4674-b7b3-e735c7a3368c)

**Comment by Segelzwerg** [comment]
@iTitus with the new layout, can we consider this done?

**Comment by iTitus** [comment]
This is a visual thing.
If you think the align is enough then this is done.
![image](https://github.com/user-attachments/assets/ded3f1d9-2a67-4329-86e6-d84f9edeece3)

**Comment by Segelzwerg** [comment]
> This is a visual thing.
> If you think the align is enough then this is done.
> ![image](https://github.com/user-attachments/assets/ded3f1d9-2a67-4329-86e6-d84f9edeece3)
> 

I'll ask my test user group.

**Comment by Segelzwerg** [comment]
The user liked it. So, closing it for now.
