### ISSUE TITLE
BUG: wrong form

### ISSUE THREAD

**Issue by Segelzwerg** [Segelzwerg/Rechnung#189]
In the InvoiceUpdate View, if the `Create Invoice` button is clicked, the Invoice Item Creation View pops up.

It is expected a form for a new invoice will be created.

![image](https://github.com/user-attachments/assets/103e0b3b-6d5c-4a85-9b61-5d64f9de8da4)

**Comment by iTitus** [comment]
im not sure how this happened, can you give reproduction steps?

**Comment by Segelzwerg** [comment]
> im not sure how this happened, can you give reproduction steps?

Got to an invoice `/invoice/<invoice-id>` and then click on `Create Invoice`.

However, I can't reproduce it anymore :o

**Comment by Segelzwerg** [comment]
> > im not sure how this happened, can you give reproduction steps?
> 
> Got to an invoice `/invoice/<invoice-id>` and then click on `Create Invoice`.
> 
> However, I can't reproduce it anymore :o

Oh I can now. It is weird bug:

Go to `/invoice/<invoice-id>`
Click on any `Update`-Button for an existing item.
Click on `Create Invoice`.

**Comment by Segelzwerg** [comment]
After step 2 the URL changes to `http://0.0.0.0:8000/invoice/3/item/2`

**Comment by iTitus** [comment]
i see
