### ISSUE TITLE
Improve Bank Account model, form and validation

### ISSUE THREAD

**Issue by iTitus** [Segelzwerg/Rechnung#236]
Add bank account owner as model field.
BIC should be optional and derived from IBAN if possible.
It should be possible to enter IBAN/BIC with spaces (from human readable format).

IBAN and BIC should be saved and represented in normalized formats:
 - convert to schwifty.IBAN and schwifty.BIC to remove spaces and fill up missing characters
 - and then either keep it as as IBAN/BIC objects or convert back to str if required.
 
End goal is to have the same representation of IBAN+BIC in the model and db no matter how it was entered: with or without spaces, with or without filler characters, explicit or derived BIC...
 
 
error caused by missing normalization/input validation:
![image](https://github.com/user-attachments/assets/28039c1e-e073-4852-8d8a-007b96e12b1c)

**Comment by iTitus** [comment]
Do we want to explicitly save the BIC even when it is derivable from the IBAN?

**Comment by Segelzwerg** [comment]
> Do we want to explicitly save the BIC even when it is derivable from the IBAN?

No, only if we cannot derive it. However, I'm not sure if that is less error prune.
