### ISSUE TITLE
FEATURE: delete button in invoice detail view

### ISSUE THREAD

**Issue by Segelzwerg** [Segelzwerg/Rechnung#50]

**Comment by iTitus** [comment]
I think this was done in #178

**Comment by Segelzwerg** [comment]
![image](https://github.com/user-attachments/assets/58b10967-fec0-44dd-8974-fdb648170ac2)
Nope ;)

**Comment by Segelzwerg** [comment]
> Oh my bad you want to delete the invoice itself. Is that even a thing we want to do? See #157 #231

Maybe for drafts, that are not final? And prohibit it for final ones.
